apiVersion: apps/v1
kind: Deployment
metadata:
  name: xylophone
  labels:
    app: xylophone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xylophone
  template:
    metadata:
      labels:
        app: xylophone
    spec:
      containers:
      - name: xylophone
        image: susheiro/xylophone
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "1000Mi"
          requests:
            cpu: "0.25"
            memory: "250Mi"
