name: Apply Manifests

on:
  push:
    branches: ['main']

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Create kube config file
        run: |
          mkdir ~/.kube
          cat ${{ secrets.KUBE_CONFIG }} | base64 --decode > ~/.kube/config
      
      - name: Specify Kubernetes context
        run: kubectl config use-context ${{ secrets.KUBE_CONTEXT }}
        # This is the (AWS cluster) context name from the kube config file

      - name: Apply changes
        run: kubectl apply -f ./

# test comment